apiVersion: v1
kind: PersistentVolume
metadata:
  name: techcorp-pv
  labels:
    type: local
    app: techcorp
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/techcorp"
